FROM node:22-alpine

WORKDIR /app

ARG AGENT_ID
ARG ELEVENLABS_API_KEY
ARG SERVICE_PORT=3000

ENV AGENT_ID=${AGENT_ID}
ENV ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
ENV SERVICE_PORT=${SERVICE_PORT}

COPY package*.json ./
COPY . .
RUN npm ci || npm install

RUN npm run build

EXPOSE $SERVICE_PORT

# Start the application
CMD ["npm", "start"]